# Change these first
owner: NaMiTech # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: web
    url: https://nami-tech.es/
  - name: room2learn
    url: https://nami-tech.es/room2learn-api/v1/status
  - name: Dreambook
    url: https://nami-tech.es/dreambook/health/
  - name: SmartEat
    url: https://nami-tech.es/barcodeapi/v1/status
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://nami-tech.es/wp-content/uploads/2021/09/nami-1.png
  name: NaMi Tech
  introTitle: "Status Page de los servicios de NaMi Tech"
  introMessage: Aquí puedes ver el estado en el que se encuentran los distintos servicios que ofrecemos
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
